# Generated by Django 4.2.2 on 2023-07-13 06:34

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('misg', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='courses_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='field_image')),
                ('field_Type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=30)),
                ('field_name', models.CharField(max_length=50)),
                ('about_field', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='book_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=550)),
                ('Author', models.CharField(max_length=150)),
                ('Publish_date', models.DateField(auto_now_add=True)),
                ('book_content', models.TextField()),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.category')),
            ],
        ),
    ]
