# Generated by Django 4.2.2 on 2023-07-13 07:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='book_image',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='book_pic'),
            preserve_default=False,
        ),
    ]
