# Generated by Django 4.2.2 on 2023-07-17 08:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libapp', '0002_book_table_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='book_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=266)),
                ('Last_name', models.CharField(max_length=266)),
                ('mobile_no', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
