# Generated by Django 4.2.2 on 2023-07-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_alter_book_table_book_content_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
