# Generated by Django 4.2.2 on 2023-07-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
