# Generated by Django 4.2.2 on 2023-07-17 15:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_remove_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='profile_pic'),
            preserve_default=False,
        ),
    ]
