# Generated by Django 4.2.2 on 2023-07-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0006_profile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
