# Generated by Django 4.2.2 on 2023-07-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0008_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
