# Generated by Django 4.2.2 on 2023-07-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0009_profile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='Publish_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='comment_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.TextField(max_length=2000)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.book_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.profile')),
            ],
        ),
    ]
