# Generated by Django 4.2.2 on 2023-07-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0011_comment_user_c_data_alter_comment_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_user',
            name='prop_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='libapp.profile'),
            preserve_default=False,
        ),
    ]
