# Generated by Django 4.2.2 on 2023-07-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0013_remove_comment_user_prop_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.book_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.profile')),
            ],
        ),
    ]
