# Generated by Django 4.2.2 on 2023-07-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0014_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='pb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpd', models.CharField(max_length=50)),
                ('pd', models.CharField(max_length=5000)),
            ],
        ),
    ]
