# Generated by Django 4.2.2 on 2023-07-25 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0015_pb'),
    ]

    operations = [
        migrations.CreateModel(
            name='fpd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pb',
            name='fpd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.fpd'),
        ),
    ]
