# Generated by Django 4.2.2 on 2023-07-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0017_alter_pb_pd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pb',
            old_name='fpd',
            new_name='fd',
        ),
    ]
